### ISSUE TITLE
postgresql syntax error on vote

### ISSUE THREAD

**Issue by rigid** [raduvatav/polls#91]
I'm using the 8.2.2RC1 tag from git and I get a SQL syntax error when submitting a vote resulting in an "internal server error" from owncloud:

```
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","Message":"An exception occurred while executing 'INSERT INTO oc_polls_particip(ok, id, USER, dt) VALUES(?,?,?,?)' with params [\"no\", \"jd3y0de4wtlqa1io\", \"testuser\", \"25.12.2015_12:00\"]:\n\nSQLSTATE[42601]: Syntax error: 7 FEHLER: Syntax error at \u201eUSER\u201c\nLINE 1: INSERT INTO oc_polls_particip(ok, id, USER, dt) VALUES($1,$2...\n ^","Code":0,"Trace":"
#0 \/var\/www\/hosts\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n
#1 \/var\/www\/hosts\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO oc_...', Array)\n
#2 \/var\/www\/hosts\/cloud\/lib\/private\/db\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n
#3 \/var\/www\/hosts\/cloud\/apps\/polls\/templates\/finish.php(61): OC_DB_StatementWrapper->execute(Array)\n
#4 \/var\/www\/hosts\/cloud\/apps\/polls\/templates\/main.php(204): include('\/var\/www\/hosts\/...')\n
#5 \/var\/www\/hosts\/cloud\/lib\/private\/template\/base.php(160): include('\/var\/www\/hosts\/...')\n
#6 \/var\/www\/hosts\/cloud\/lib\/private\/template\/base.php(138): OC\\Template\\Base->load('\/var\/www\/hosts\/...')\n
#7 \/var\/www\/hosts\/cloud\/lib\/private\/template.php(211): OC\\Template\\Base->fetchPage()\n
#8 \/var\/www\/hosts\/cloud\/lib\/private\/template\/base.php(121): OC_Template->fetchPage()\n
#9 \/var\/www\/hosts\/cloud\/apps\/polls\/index.php(14): OC\\Template\\Base->printPage()\n
#10 \/var\/www\/hosts\/cloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/hosts\/...')\n
#11 [internal function]: __lambda_func(Array)\n
#12 \/var\/www\/hosts\/cloud\/lib\/private\/route\/router.php(291): call_user_func('\\x00lambda_1', Array)\n
#13 \/var\/www\/hosts\/cloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/polls\/')\n
#14 \/var\/www\/hosts\/cloud\/index.php(39): OC::handleRequest()\n
#15 {main}","File":"\/var\/www\/hosts\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractPostgreSQLDriver.php","Line":66}
```

**Comment by v1r0x** [comment]
I switched from plain sql queries to owncloud's `Mapper`. I hope this will fix this error, but I don't use postgresql. Would be great if you could test the new release (will be released in a few days) and report back if you still have this error.

**Comment by mckaygerhard** [comment]
al the development are made using db's that are made for non-scalar metas.  in that freesoft never will retrain in countries like me over the privative softwre... uff

it's not necesary use postgresql for close to all db's, the problem using (i mean mysql) its that mysql and other like m$ breaks sql standars.. its all.. easy!

**Comment by v1r0x** [comment]
@rigid Please test the new release at [https://github.com/v1r0x/polls/](https://github.com/v1r0x/polls/).
